"""Generate a reproducible exploratory data analysis report."""

from __future__ import annotations

import argparse
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt

from src.utils import load_config, load_dataset


def analyze(config_path: str) -> list[Path]:
    config, project_root = load_config(config_path)
    frame = load_dataset(config, project_root)
    reports_dir = project_root / "reports"
    figures_dir = reports_dir / "figures"
    figures_dir.mkdir(parents=True, exist_ok=True)
    target = config["data"]["target"]

    target_path = figures_dir / "target_distribution.png"
    counts = frame[target].value_counts().sort_index()
    counts.rename(index={0: "No churn", 1: "Churn"}).plot.bar(
        color=["#4c78a8", "#f58518"]
    )
    plt.title("Target distribution")
    plt.ylabel("Customers")
    plt.xticks(rotation=0)
    plt.tight_layout()
    plt.savefig(target_path, dpi=160)
    plt.close()

    tenure_path = figures_dir / "tenure_by_churn.png"
    frame.boxplot(column="tenure", by=target, grid=False)
    plt.suptitle("")
    plt.title("Tenure by churn class")
    plt.xlabel("Churn (0 = no, 1 = yes)")
    plt.ylabel("Months")
    plt.tight_layout()
    plt.savefig(tenure_path, dpi=160)
    plt.close()

    missing = frame.isna().sum()
    missing = missing[missing > 0].sort_values(ascending=False)
    numeric_summary = frame[config["features"]["numeric"]].describe().round(2)
    churn_rate = frame[target].mean()
    duplicate_ids = int(frame[config["data"]["id_column"]].duplicated().sum())
    report = f"""# Exploratory data analysis — IBM Telco Customer Churn

This report is generated by `python -m src.analyze --config configs/config.yaml`.

## Dataset quality

- Rows: **{len(frame):,}**
- Input columns: **{len(frame.columns) - 1}** plus the target
- Churn rate: **{churn_rate:.2%}**
- Duplicate customer IDs: **{duplicate_ids}**
- Missing values after parsing: **{int(frame.isna().sum().sum())}** (the original whitespace-only `TotalCharges` values are treated as missing and imputed inside the training pipeline)

### Missing values by column

{missing.to_frame("missing_rows").to_markdown() if not missing.empty else "No missing values."}

### Numeric summary

{numeric_summary.to_markdown()}

## Interpretation

The target is imbalanced but not rare, so ROC-AUC is used for model selection and average precision, recall, precision, F1 and accuracy are retained for final interpretation. The split is stratified. All imputation, scaling, and one-hot encoding are fitted only on training folds through the scikit-learn pipeline, which prevents preprocessing leakage.

The figures in `reports/figures/` show the target distribution and the relationship between tenure and churn. Final error analysis is available after evaluation in `artifacts/predictions.csv`.
"""
    report_path = reports_dir / "eda_report.md"
    report_path.write_text(report, encoding="utf-8")
    return [report_path, target_path, tenure_path]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--config", default="configs/config.yaml")
    return parser.parse_args()


if __name__ == "__main__":
    outputs = analyze(parse_args().config)
    print("Generated EDA artifacts:")
    for output in outputs:
        print(f"- {output}")
